repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
    - id: clang-format
      name: clang-format
      entry: clang-format
      language: system
      files: \.(cpp|h)$
      args: ["-i"]
