# This file selects the correct job definition based on system and buildType.

parameters:
  debug: 'false'

jobs:

- ${{ if eq(parameters.name, 'Windows') }}:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.name }}
    pool:
      vmImage: 'windows-latest'
    steps:
    - template: windows.yml
      parameters:
        nuget_version: '5.4.0'
        ${{ if eq(parameters.debug, 'true') }}:
          configuration: 'debug'
          path: 'Debug'
        ${{ if eq(parameters.debug, 'false') }}:
          configuration: 'release'
          path: 'Release'

- ${{ if eq(parameters.name, 'Linux') }}:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.name }}
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install clang-9
        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-9 50
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-9 50
        clang-9 --version
        clang++-9 --version
        which clang-9
        which clang++-9
    - template: nix.yml
      parameters:
        artifactName: linux-drop
        ${{ if eq(parameters.debug, 'true') }}:
          configuration: 'Debug'
        ${{ if eq(parameters.debug, 'false') }}:
          configuration: 'Release'

- ${{ if eq(parameters.name, 'macOS') }}:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.name }}
    pool:
      vmImage: 'macos-latest'
    steps:
    - template: nix.yml
      parameters:
        artifactName: macos-drop
        ${{ if eq(parameters.debug, 'true') }}:
          configuration: 'Debug'
        ${{ if eq(parameters.debug, 'false') }}:
          configuration: 'Release'
