# This defines a pipeline to build on macOS in Debug mode.

trigger:
  batch: true
  branches:
    include:
    - master

stages:
  - stage: build
    displayName: Build
    jobs:
    - template: jobs.yml
      parameters:
        debug: true
        name: macOS